spring:
  application:
    name: robot-microservice
  cloud:
    config: 
      uri: http://xignzi:8100/

server:
  port: 8080

eureka:
  host: 
    name: xignzi
  client: 
    serviceUrl:
      defaultZone: http://xignzi:8761/eureka/
  instance: 
    prefer-ip-address: true
    instance-id: ${spring.application.name} ${spring.cloud.client.hostname}:${server.port}
    healthcheck:
      enable: true
