server:
  port: 8070

spring: 
  application:
    name: user
  zipkin:
    base-url: http://xignzi:9000
  sleuth:
    sampler:
      percentage: 1
  rabbitmq:
    host: 172.16.102.12
    port: 5672
    username: guest
    password: guest


logging: 
  level: 
    org.springframework.sleuth: DEBUG
    org.springframework.zipkin: DEBUG
    
eureka:
  host: 
    name: 172.16.102.12
  client: 
    serviceUrl:
      defaultZone: http://172.16.102.12:8762/eureka/
  instance: 
    prefer-ip-address: true
    instance-id: ${spring.application.name} ${spring.cloud.client.hostname}:${server.port}
    healthcheck:
      enable: true


  

feign:
  hystrix:
    enabled: true
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
