version: 4.0
management: 
  security: 
    enabled: false
server:
  port: 8070
eureka:
  host: 
    name: xignzi
  client: 
    serviceUrl:
      defaultZone: http://xignzi:8761/eureka/
  instance: 
    prefer-ip-address: true
    instance-id: ${spring.application.name} ${spring.cloud.client.hostname}:${server.port}
    healthcheck:
      enable: true

spring: 
  application:
    name: user-microservice
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  

feign:
  hystrix:
    enabled: true
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
