server:
  port: 9411

eureka:
  host: 
    name: 172.16.102.12
  client: 
    serviceUrl:
      defaultZone: http://172.16.102.12:8762/eureka/
  instance: 
    prefer-ip-address: true
    instance-id: ${spring.application.name} ${spring.cloud.client.hostname}:${server.port}
    healthcheck:
      enable: true
      
spring: 
  application:
    name: zipkin
  sleuth:
    enabled: false
    sampler:
      percentage: 1
  rabbitmq:
    host: 172.16.102.12
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://172.16.170.61:3306/aca0a6ab0a?autoReconnect=true&useUnicode=true&characterEncoding=GB2312&useOldAliasMetadataBehavior=true
    driverClassName: com.mysql.jdbc.Driver
    username: aca0a6ab0a
    password: 5@f@974e
    #initialize: true
    #continue-on-error: true

zipkin:
  storage: 
    type: mysql


  
