spring:
  rabbitmq:
    host: 172.16.102.12
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://172.16.170.61:3306/aca0a6ab0a?autoReconnect=true&useUnicode=true&characterEncoding=GB2312&useOldAliasMetadataBehavior=true
    driverClassName: com.mysql.jdbc.Driver
    username: aca0a6ab0a
    password: 5@f@974e

eureka:
  host: 
    name: 172.16.102.12
  client: 
    serviceUrl:
      defaultZone: http://172.16.102.12:8762/eureka/
  instance: 
    prefer-ip-address: true
    instance-id: ${spring.application.name} ${spring.cloud.client.hostname}:${server.port}
    healthcheck:
      enable: true

zuul: 
  routes:
      user: 
        path: /api/user/**
        serviceId: user-microservice
      robot: 
        path: /api/robot/**
        serviceId: robot-microservice
#  TokenFilter:
#    post: 
#      disable: false
#  ValidTokenFilter:
#    post: 
#      disable: false
      
      
#security:
#  user:
#    password: user  # 直接登录时的密码
#  ignored: /
#  sessions: never   # session策略
#  oauth2:
#    sso:
#      loginPath: /login   # 登录路径
#    client:
#      clientId: d3a54d3cc38952aa0fa4
#      clientSecret: e9b6d369ba39e5f5e58134b0de6ba27145f2cd43
#      accessTokenUri: https://github.com/login/oauth/access_token
#      userAuthorizationUri: https://github.com/login/oauth/authorize
#    resource:
#      userInfoUri: https://api.github.com/user
#      preferTokenInfo: false
      
